[package]
name = "rodio"
version = "0.1.0"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
description = "Audio playback library"
tags = ["audio", "playback", "gamedev"]
license = "Apache2"

[dependencies]
cpal = "0.1.1"
hound = "1.0.0"
lazy_static = "0.1.12"
